name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Frontend
        run: |
          cd ciudad-blog-frontend
          npm install
          npm run build

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
    
      - name: Verify Docker
        run: |
          docker --version
          docker compose version

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build Backend
        run: |
          cd ciudad-blog-backend
          ./mvnw clean package -DskipTests

      - name: Build Docker Containers
        run: |
          docker compose -f docker/docker-compose.yml build
          
      - name: Start containers
        run: |
          docker compose -f docker/docker-compose.yml up -d

      - name: List running containers
        run: |
          docker ps
      
      - name: Tag backend image
        run: |
          docker tag backend jubileos/ciudad-blog-backend:latest

      - name: Push backend image
        run: |
          docker push jubileos/ciudad-blog-backend:latest      